### ISSUE TITLE
mixin.unstream.pathfinding optimization makes it a lot harder for mobs to pathfind player

### ISSUE THREAD

**Issue by VindSole** [Tater-Certified/Potatoptimize#21] opened 2024-07-09 00:57 UTC
Mobs constantly lose track/become neutral and often run in circles when this optimization is enabled, more evident on mansions probably because of wool carpets.

**Comment by QPCrummer** [comment] 2024-07-09 03:44
It should make absolutely no difference if the code uses Stream API or not, so this means something was reimplemented incorrectly. I will have a fix for this tomorrow.

**Comment by QPCrummer** [comment] 2024-07-10 00:05
This issue should be fixed in the latest version: https://modrinth.com/mod/potatoptimize/version/mc1.21-0.0.1-dev.5

Can you please ensure that it is working as intended?

**Comment by VindSole** [comment] 2024-07-10 00:26
Can confirm is working!

**Comment by QPCrummer** [comment] 2024-07-10 00:29
Cool!

**Closed by QPCrummer** 2024-07-10 00:29 UTC
